services:
- &f8a-emr-deployment_def
  hash: be1fda7cf1bb938fe12f20654cbc9b0f13f50373
  hash_length: 7
  name: f8a-emr-deployment
  environments:
  - name: staging
    parameters:
      CPU_REQUEST: 250m
      CPU_LIMIT: 250m
      MEMORY_REQUEST: 250Mi
      MEMORY_LIMIT: 250Mi
      REPLICAS: 1
      DOCKER_REGISTRY: quay.io
      DOCKER_IMAGE: openshiftio/rhel-fabric8-analytics-f8a-emr-deployment
  - name: production
    parameters:
      CPU_REQUEST: 250m
      CPU_LIMIT: 250m
      MEMORY_REQUEST: 250Mi
      MEMORY_LIMIT: 250Mi
      REPLICAS: 1
      DOCKER_REGISTRY: quay.io
      DOCKER_IMAGE: openshiftio/rhel-fabric8-analytics-f8a-emr-deployment
  path: /openshift/template.yaml
  url: https://github.com/fabric8-analytics/f8a-emr-deployment/
