services:
- &f8a-emr-deployment_def
  hash: 9de445442ab3de9ebd3d9cf96fd263757dd75bca
  hash_length: 7
  name: f8a-emr-deployment
  environments:
  - name: staging
    parameters:
      CPU_REQUEST: 125m
      CPU_LIMIT: 250m
      MEMORY_REQUEST: 125Mi
      MEMORY_LIMIT: 250Mi
      REPLICAS: 1
      DOCKER_REGISTRY: quay.io
      DOCKER_IMAGE: openshiftio/rhel-fabric8-analytics-f8a-emr-deployment
  - name: production
    parameters:
      CPU_REQUEST: 125m
      CPU_LIMIT: 250m
      MEMORY_REQUEST: 125Mi
      MEMORY_LIMIT: 250Mi
      REPLICAS: 1
      DOCKER_REGISTRY: quay.io
      DOCKER_IMAGE: openshiftio/rhel-fabric8-analytics-f8a-emr-deployment
  path: /openshift/template.yaml
  url: https://github.com/fabric8-analytics/f8a-emr-deployment/
